export NVM_DIR=~/.nvm
export SCALAENV_ROOT=/usr/local/var/scalaenv
export JENV_ROOT=/usr/local/opt/jenv
export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home
export PRIV=~/Priv
export PROJECTS=~/Projects
export OSX_CONFIG=$PRIV/dotfiles
export MOBBE_HOME=$PRIV/Mobbe
export ANDROID_HOME=~/Library/Android/sdk/
# export PATH="$PATH:`yarn global bin`"
# export PATH="$HOME/.rvm/bin:$PATH"
# export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"
# export PATH="/usr/local/opt/go/libexec/bin:$PATH"
export PATH="$HOME/bin:$PATH"
# export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export ENVIRONMENT_NAME=DEV
export GOROOT=~/Priv/Go
export GOPATH=/Users/arturskowronski/Priv/ledger
export GRADLE_USER_HOME=/Users/arturskowronski/.gradle
export TLS="$PROJECTS"